version: '3'
services:
  backend-microservice:
    build:
      context: "./apps/backend-microservice"
      dockerfile: "Dockerfile"
      args:
        UID: "${UID}"
        GID: "${GID}"
    working_dir: "/app"
    restart: "unless-stopped"
    environment:
      NODE_ENV: "development"
      HOST: "0.0.0.0"
      PORT: "3000"
      DATABASE_URL: "mysql://root:root@mysql:3306/app"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - "./apps/backend-microservice:/app:delegated"
    command: "bash -c 'yarn && yarn start:dev'"
    networks:
      - "app"
    depends_on:
      - "mysql"

  mysql:
    image: "mysql:8"
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - "app"


networks:
  app: null

volumes:
  mysql: null
